distributed_type: DEEPSPEED
mixed_precision: "bf16"
downcast_bf16: 'no'
deepspeed_config:
  bf16:
    enabled: "auto"
  optimizer:
    type: AdamW
    params:
      lr: "auto"
      betas: "auto"
      eps: "auto"
      weight_decay: "auto"
  scheduler:
    type: WarmupLR
    params:
      warmup_min_lr: 1.0e-06
      warmup_max_lr: 1.0e-05
      warmup_num_steps: 50
  zero_optimization:
    stage: 3
    overlap_comm: true
    contiguous_gradients: true
    sub_group_size: 1.0e+09
    reduce_bucket_size: "auto"
    stage3_prefetch_bucket_size: "auto"
    stage3_param_persistence_threshold: "auto"
    stage3_max_live_parameters: 1.0e+09
    stage3_max_reuse_distance: 1.0e+09
    stage3_gather_16bit_weights_on_model_save: true
  gradient_accumulation_steps: 4
  gradient_clipping: "auto"
  steps_per_print: "auto"
  train_batch_size: "auto"
  train_micro_batch_size_per_gpu: "auto"
  wall_clock_breakdown: false
  deepspeed_multinode_launcher: "standard"